defaults:
  - override hydra/launcher: joblib
env_id: CartPole-v1
batch_size: 256
n_episodes: 500
warm_up_episodes: 50
gamma: 0.99
train_steps: 5
target_update_freq: 10
pi_lr: 3e-4
vf_lr: 1e-3
replay_buffer_capacity: 10000
width: 8
grid: 5
method: "KAN"
seed: 0
log_interval: 10